<#
.SYNOPSIS
    Regenerates docs\POLICIES.md - the plain-language reference of every setting,
    preset and blocklist group - from the catalog inside Brave-Free-Origin.ps1.

.DESCRIPTION
    The reference is generated, never hand-edited, so it cannot drift from what
    the app actually writes. The script starts the app in its sandboxed
    self-test mode (no window, no UAC, no registry or hosts changes), lets the
    app build its own model, and renders that model as Markdown in English.

    Run it after changing the catalog, and commit the result:

        powershell.exe -NoProfile -ExecutionPolicy Bypass -File tools\Export-PolicyDocs.ps1

    CI regenerates the file and fails when it differs from the committed copy.

.PARAMETER OutFile
    Where to write the Markdown. Default: docs\POLICIES.md next to the repo root.
#>
[CmdletBinding()]
param(
    [string]$OutFile
)

# ---- Mode 1: started from a shell -> launch the app in sandbox mode with this file as the hook ----
if (-not (Get-Variable -Name SelfTestMode -Scope Script -ErrorAction SilentlyContinue) -or -not $script:SelfTestMode) {
    $repoRoot = Split-Path -Parent $PSScriptRoot
    if (-not $OutFile) { $OutFile = Join-Path $repoRoot 'docs\POLICIES.md' }
    $outDir = Split-Path -Parent $OutFile
    if ($outDir -and -not (Test-Path -LiteralPath $outDir)) { [void](New-Item -ItemType Directory -Path $outDir -Force) }

    $env:BFO_DOCS_OUT = [System.IO.Path]::GetFullPath($OutFile)
    $settings = Join-Path ([System.IO.Path]::GetTempPath()) ('bfo-docs-' + [guid]::NewGuid().ToString('N').Substring(0, 8) + '\settings.json')
    try {
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $repoRoot 'Brave-Free-Origin.ps1') `
            -Lang en-US -BfoSettingsPath $settings -SelfTest $PSCommandPath
        if ($LASTEXITCODE -ne 0) { throw "The app exited with code $LASTEXITCODE while building the reference." }
    } finally {
        Remove-Item Env:\BFO_DOCS_OUT -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath (Split-Path -Parent $settings) -Recurse -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Wrote $OutFile"
    return
}

# ---- Mode 2: running inside the app (dot-sourced by -SelfTest) ------------------------------------
$out = $env:BFO_DOCS_OUT
if (-not $out) { throw 'BFO_DOCS_OUT is not set; run tools\Export-PolicyDocs.ps1 instead of calling the hook directly.' }

$md = New-Object System.Text.StringBuilder
function Add-Line { param([string]$Text = '') [void]$md.Append($Text).Append("`n") }

# Table cells must be one line and must not contain pipes.
function Format-Cell {
    param([string]$Text)
    return (($Text -replace '\r?\n', ' ') -replace '\|', '\|').Trim()
}

$presetInfo = @(
    @{ Id = 'Minimal';        Code = 'Q'; Short = 'Quick' }
    @{ Id = 'Origin';         Code = 'O'; Short = 'Origin' }
    @{ Id = 'Recommended';    Code = 'R'; Short = 'Rec.' }
    @{ Id = 'Performance';    Code = 'B'; Short = 'Boost' }
    @{ Id = 'MaxPerformance'; Code = 'X'; Short = 'Max perf.' }
    @{ Id = 'MaxPrivacy';     Code = 'P'; Short = 'Max priv.' }
)
$presetOrder = @('Minimal', 'Recommended', 'Origin', 'Performance', 'MaxPerformance', 'MaxPrivacy')

$policyCount = @($script:Items | Where-Object { $_.Kind -eq 'Policy' }).Count
$pageCount   = @($script:PolicyPageOrder | Where-Object { $script:PolicyPages.Contains($_) }).Count

Add-Line '<!-- GENERATED by tools/Export-PolicyDocs.ps1 from Brave-Free-Origin.ps1. Do not edit by hand. -->'
Add-Line
Add-Line '# Brave Free Origin - what every setting does'
Add-Line
Add-Line ("This is the complete list of what Brave Free Origin v{0} can change: **{1} Brave policies** on {2} pages, {3} presets, a DNS blocklist and the optional updater switches. Everything here is reversible: unticking a row and pressing **Apply** removes it, and **Restore stock** removes everything the tool ever set." -f $script:AppVersion, $policyCount, $pageCount, $presetOrder.Count)
Add-Line
Add-Line ("> **Checked against Brave {0} (Chromium {1}) on {2}.** Brave adds, renames and retires policies over time. On a newer Brave a few rows may be renamed or gone (Brave ignores a policy it does not know, so nothing breaks); on an older one some rows may not exist yet. Open ``brave://policy`` to see exactly what your Brave accepted." -f $script:CatalogBrave, $script:CatalogBraveMajor, $script:CatalogDate)
Add-Line
Add-Line '## How to read the tables'
Add-Line
Add-Line '- **Ticked** means this tool enforces the row. For most rows that switches a feature **off** (the title says so: "Turn off ..."). Rows marked **keeps on** lock a protection Brave already uses by default, so nothing can silently weaken it. Rows marked **sets** write a specific value.'
Add-Line '- **Unticked** means the tool sets nothing and Brave decides. Pressing Apply removes the policy this tool wrote earlier.'
Add-Line '- **Set elsewhere** (in the Status column of the app) means the policy already holds a value this tool would never write, for example one set by your organization. Apply and Restore stock leave it alone unless you tick the row. A value identical to one this tool writes cannot be told apart from its own.'
Add-Line '- **Risk** says what an everyday user could lose: *Safe* and *Low* are fine for everybody; *Medium* and *High* change how Brave behaves, so read the description first.'
Add-Line '- **Policy** is the registry value name under `HKLM\SOFTWARE\Policies\BraveSoftware\Brave` (one key for Stable, Beta, Nightly and Dev). It is also the name you will see in `brave://policy`.'
Add-Line '- The preset columns show which presets tick the row: **Quick** = Quick Debloat, **Rec.** = Recommended, **Origin** = Origin Mode, **Boost** = Privacy + Boost, **Max perf.** = Max Performance, **Max priv.** = Max Privacy.'
Add-Line

# ---- presets ----
Add-Line '## Presets'
Add-Line
Add-Line 'A preset only ticks boxes; nothing is written until you press **Apply**. Presets never touch the updater switches, the search engine / new tab / startup overrides or the scriptlet tool.'
Add-Line
Add-Line '| Preset | What it does | Risk | Policies ticked | Hosts groups ticked |'
Add-Line '| --- | --- | --- | ---: | ---: |'
foreach ($id in $presetOrder) {
    $sel = Get-PresetSelection -Preset $id
    Add-Line ("| **{0}** | {1} | {2} | {3} | {4} |" -f (Format-Cell (TEn "preset.$id.name")), (Format-Cell (TEn "preset.$id.description")), (Format-Cell (TEn "preset.$id.risk")), $sel.Policies.Count, $sel.Hosts.Count)
}
Add-Line ("| **{0}** | {1} | {2} | 0 | 0 |" -f (Format-Cell (TEn 'preset.None.name')), (Format-Cell (TEn 'preset.None.description')), (Format-Cell (TEn 'preset.None.risk')))
Add-Line

# ---- policy pages ----
$kindNote = @{ Off = 'feature off'; On = 'protection on'; Set = 'value set' }
foreach ($pageId in $script:PolicyPageOrder) {
    if (-not $script:PolicyPages.Contains($pageId)) { continue }
    $defs = @($script:PolicyPages[$pageId])
    Add-Line ("## {0}" -f (TEn "page.$pageId.title"))
    Add-Line
    Add-Line (TEn "page.$pageId.intro")
    Add-Line
    Add-Line '| Setting | What it does | Policy | Writes | Risk | Quick | Rec. | Origin | Boost | Max perf. | Max priv. |'
    Add-Line '| --- | --- | --- | --- | --- | :---: | :---: | :---: | :---: | :---: | :---: |'
    foreach ($def in $defs) {
        $value = if ($def.Type -eq 'STRING') { '`"' + $def.Value + '"`' } else { '`' + $def.Value + '`' }
        $note  = $kindNote[$def.Kind]
        if ($def.Choices) { $note = 'you choose'; $value = '`' + (($def.Choices.Values | ForEach-Object { $_ }) -join ' / ') + '`' }
        if ($def.Lock)    { $note += ", already Brave's default" }
        $marks = foreach ($code in @('Q', 'R', 'O', 'B', 'X', 'P')) { if ($def.Presets.Contains($code)) { 'x' } else { '' } }
        Add-Line ('| {0} | {1} | `{2}` | {3} ({4}) | {5} | {6} |' -f
            (Format-Cell (TEn "policy.$($def.Name).title")),
            (Format-Cell (TEn "policy.$($def.Name).description")),
            $def.Name, $value, $note,
            (Format-Cell (TEn "risk.$($def.Risk)")),
            ($marks -join ' | '))
    }
    Add-Line
}

# ---- overrides ----
Add-Line ("## {0}" -f (TEn 'page.overrides.title'))
Add-Line
Add-Line (TEn 'page.overrides.intro')
Add-Line
Add-Line '| Override | What it writes |'
Add-Line '| --- | --- |'
Add-Line ('| {0} | `DefaultSearchProviderEnabled`, `DefaultSearchProviderName`, `DefaultSearchProviderKeyword`, `DefaultSearchProviderSearchURL`, `DefaultSearchProviderSuggestURL` |' -f (Format-Cell (TEn 'searchTab.secSearch')))
Add-Line ('| {0} | `NewTabPageLocation` |' -f (Format-Cell (TEn 'searchTab.secNtp')))
Add-Line ('| {0} | `RestoreOnStartup` and `RestoreOnStartupURLs` |' -f (Format-Cell (TEn 'searchTab.secStartup')))
Add-Line
Add-Line 'These are off until you tick their box, presets never change them, and they win over the matching rows on the other pages.'
Add-Line

# ---- hosts ----
Add-Line ("## {0}" -f (TEn 'page.hosts.title'))
Add-Line
Add-Line (TEn 'page.hosts.intro')
Add-Line
Add-Line '| Group | What it blocks | Risk | Domains | Pre-ticked by |'
Add-Line '| --- | --- | --- | --- | --- |'
foreach ($h in $script:HostsBlocks) {
    $by = @($presetOrder | Where-Object { $script:PresetHosts.ContainsKey($_) -and ($script:PresetHosts[$_] -contains $h.Id) } | ForEach-Object { TEn "preset.$_.name" })
    Add-Line ('| {0} | {1} | {2} | {3} | {4} |' -f
        (Format-Cell (TEn "hosts.$($h.Id).name")),
        (Format-Cell (TEn "hosts.$($h.Id).description")),
        (Format-Cell (TEn "risk.$($h.Risk)")),
        (($h.Domains | ForEach-Object { '`' + $_ + '`' }) -join ', '),
        $(if ($by.Count -gt 0) { Format-Cell ($by -join ', ') } else { 'no preset' }))
}
Add-Line
Add-Line 'The hosts file matches exact names only (no wildcards), so this is a second line of defence behind the policies above. Only the block between the `# === Brave-Free-Origin START` and `# === Brave-Free-Origin END ===` lines is ever edited; everything else in the file is preserved byte for byte, and a backup is saved first.'
Add-Line

# ---- updater ----
Add-Line ("## {0}" -f (TEn 'page.updater.title'))
Add-Line
Add-Line (TEn 'page.updater.intro')
Add-Line
Add-Line ('> ' + (TEn 'updater.warning'))
Add-Line
Add-Line '| Item | What it does |'
Add-Line '| --- | --- |'
foreach ($t in $script:UpdaterTaskDefs)    { Add-Line ('| {0} (scheduled task `{1}`) | {2} |' -f (Format-Cell (TEn "task.$($t.Id).title")), $t.Pattern, (Format-Cell (TEn "task.$($t.Id).description"))) }
foreach ($s in $script:UpdaterServiceDefs) { Add-Line ('| {0} (Windows service `{1}`) | {2} |' -f (Format-Cell (TEn "service.$($s.Id).title")), $s.Name, (Format-Cell (TEn "service.$($s.Id).description"))) }
Add-Line

[System.IO.File]::WriteAllText($out, $md.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("Wrote {0} ({1} policies, {2} pages)" -f $out, $policyCount, $pageCount)
